services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: HMSDB
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7041:7041"
      - "5010:5010"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7041;http://+:5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/HMS.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    # 
    
  migrate-database:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection="Server=mysql;Database=HMSDB;User=root;Password=P@ssw0rd;"
    command: >
      sh -c "
        dotnet tool install --global dotnet-ef --version 8.0.0 &&
        export PATH=$PATH:/root/.dotnet/tools &&
        dotnet ef database update HMS.csproj"
    restart: "no"

volumes:
  mysql_data:
